**step1 : import packages**

In [1]:
import pandas as pd  # data framwork
import numpy as np   # mathmetical operation
import matplotlib.pyplot as plt   # grafical visuali
import seaborn as sns

**step2 : Create a Df using list**

In [2]:
names=['Ramesh','Suresh','Sathish']
pd.DataFrame(names)

         0
0   Ramesh
1   Suresh
2  Sathish

**step3 : i want to change the index**

In [6]:
names=['Ramesh','Suresh','Sathish']
ide=['A','B','C']
pd.DataFrame(names,ide)
# pd.DataFrame(data,index)

         0
A   Ramesh
B   Suresh
C  Sathish

In [ ]:
**step4 :

**step5 : Data and columns**

In [9]:
names=['Ramesh','Suresh','Sathish']
cols=['Name']
pd.DataFrame(names,columns=cols)

      Name
0   Ramesh
1   Suresh
2  Sathish

**step6 : Multiple Columns**

In [15]:
names=['Ramesh','Suresh','Sathish']
age=[20,22,24]
cols=['Name','Age']
df=pd.DataFrame(zip(names,age),columns=cols)
df

      Name  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

**step7 :add a new column to alreday  existed df**
- in above first we  have taken data

- then created a dataframe

- now we want to add new data based on requirement

In [16]:
city =['Hyd','Pune','Blr']
df['City']=city
df

      Name  Age  City
0   Ramesh   20   Hyd
1   Suresh   22  Pune
2  Sathish   24   Blr

In [17]:
mark=[80,50,75]
df['Mark']=mark
df

      Name  Age  City  Mark
0   Ramesh   20   Hyd    80
1   Suresh   22  Pune    50
2  Sathish   24   Blr    75

**step8 : update the columns with new values**

In [18]:
df['Mark']=[380,445,499]
df

      Name  Age  City  Mark
0   Ramesh   20   Hyd   380
1   Suresh   22  Pune   445
2  Sathish   24   Blr   499

**step9 :Create empty dataframe and add the columns**

In [20]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [21]:
df=pd.DataFrame()
df['Name']=['Ramesh','Suresh','Sathish']
df['Age']=[20,22,24]
df['City']=['Odi','Hyd','Blr']
df

      Name  Age City
0   Ramesh   20  Odi
1   Suresh   22  Hyd
2  Sathish   24  Blr

**step10 : Create a dataframe using Dictonary**

In [3]:
d={'Name':['Ramesh','Suresh','Sathish'],
   'Age':[20,22,24],
   'City':['Odi','Hyd','Blr']}
df=pd.DataFrame(d)
df

      Name  Age City
0   Ramesh   20  Odi
1   Suresh   22  Hyd
2  Sathish   24  Blr

In [24]:
d={'Name':'Ramesh',
   'Age' : 20 }
pd.DataFrame(d,index=[0])

     Name  Age
0  Ramesh   20

**step11 : Save the DataFrame**

In [25]:
# file handling session
# directory // filename.ext
# filename.ext
# we are saving dataframes
#   .csv  or .xlsx
df.to_csv('data.csv')

In [28]:
df.to_excel('data.xlsx')

**how to read the dataframe**

In [6]:
# in order to read the data 
# filename.ext
# open(mobox-short.txt).read()
# open(dummy.txt,mode).write('hello')
# data.csv   data.xlsx
pd.read_csv('data.csv')

   Unnamed: 0     Name  Age City
0           0   Ramesh   20  Odi
1           1   Suresh   22  Hyd
2           2  Sathish   24  Blr

In [4]:
df

      Name  Age City
0   Ramesh   20  Odi
1   Suresh   22  Hyd
2  Sathish   24  Blr

In [5]:
pd.read_excel('data.xlsx')

   Unnamed: 0     Name  Age City
0           0   Ramesh   20  Odi
1           1   Suresh   22  Hyd
2           2  Sathish   24  Blr

In [7]:
d={'Name':['Ramesh','Suresh','Sathish'],
   'Age':[20,22,24],
   'City':['Odi','Hyd','Blr']}
df=pd.DataFrame(d)
df

      Name  Age City
0   Ramesh   20  Odi
1   Suresh   22  Hyd
2  Sathish   24  Blr

In [8]:
df.to_csv('data1.csv',index=False)

In [9]:
pd.read_csv('data1.csv')

      Name  Age City
0   Ramesh   20  Odi
1   Suresh   22  Hyd
2  Sathish   24  Blr

In [10]:
df.to_excel('data1.xlsx',index=False)

In [11]:
pd.read_excel('data1.xlsx')

      Name  Age City
0   Ramesh   20  Odi
1   Suresh   22  Hyd
2  Sathish   24  Blr

In [12]:
gender=['M','M','M']
df['Gender']=gender
df

      Name  Age City Gender
0   Ramesh   20  Odi      M
1   Suresh   22  Hyd      M
2  Sathish   24  Blr      M

**step13 : Drop the column**
- labels: 'IndexLabel | None' = None, *,
- axis: 'Axis' = 0,
- index: 'IndexLabel | None' = None,
- columns: 'IndexLabel | None' = None,
- level: 'Level | None' = None,
- inplace: 'bool' = False,
- errors: 'IgnoreRaise' = 'raise',

In [14]:
# if i want to drop a index
# i need to use index argument
df.drop(index=0)

      Name  Age City Gender
1   Suresh   22  Hyd      M
2  Sathish   24  Blr      M

In [15]:
df

      Name  Age City Gender
0   Ramesh   20  Odi      M
1   Suresh   22  Hyd      M
2  Sathish   24  Blr      M

In [17]:
df.drop(columns='Gender')

      Name  Age City
0   Ramesh   20  Odi
1   Suresh   22  Hyd
2  Sathish   24  Blr

In [ ]:
df.drop(index=0)
df.drop(columns='Gender')
==============================================
df.drop('Gender') # if i do not give argument leble
df.drop(0)   # 1 be come lable
==============================================
# we need to provide axis
# axis = 0 indicates index
# axis = 1 indicates columns

**inplace**

- when we do the  operation the ruselt output is not over

- means the original data frame is same as it is

- in order to do this we need use **inplace**

- by default inplace = False

- make **inplace=True** if you want overwrite result

**step14 : rename the column**

In [23]:
d={'City':'city'}
# df.rename(<mapper>,<axis>,)
df.rename(d,axis=1,inplace=True)

In [24]:
df

      Name  Age city Gender
0   Ramesh   20  Odi      M
1   Suresh   22  Hyd      M
2  Sathish   24  Blr      M

In [27]:
# create one more df
x =list(range(1, 10))
y = [i*i for i in x]
z = [i**3 for i in x]
df= pd.DataFrame(zip(x,y,z),
                 columns=['x','y','z'])
df

   x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

- len

- shape:  df.shape

- size:   df.size

- head:   df.head

- tail:   df.tail

- isnull: df.isnull

- dtypes: df.types

- info:   df.info

In [29]:
len(df)

9

In [34]:
df.shape

(9, 3)

In [35]:
df.size

27

In [36]:
df.head

<bound method NDFrame.head of    x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729>

In [37]:
df.tail

<bound method NDFrame.tail of    x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729>

In [38]:
df.isnull

<bound method DataFrame.isnull of    x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729>

In [33]:
df.dtypes

x    int64
y    int64
z    int64
dtype: object

In [39]:
df.info

<bound method DataFrame.info of    x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729>

In [40]:
df.isnull().sum()

x    0
y    0
z    0
dtype: int64

**step15:select a columns**

In [42]:
df.columns

Index(['x', 'y', 'z'], dtype='object')

In [44]:
df['x']

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: x, dtype: int64

In [45]:
df[['x','y']]

   x   y
0  1   1
1  2   4
2  3   9
3  4  16
4  5  25
5  6  36
6  7  49
7  8  64
8  9  81

In [47]:
type(df['x'])

pandas.core.series.Series

In [46]:
type(df[['x','y']])

pandas.core.frame.DataFrame

In [48]:
df['x'].shape

(9,)

In [49]:
df[['x','y']].shape

(9, 2)

In [52]:
df  # data frame
df['z']  # selecting one particular column
df['z'].values # extracting the data
df['z'].values.tolist()

[1, 8, 27, 64, 125, 216, 343, 512, 729]